### ISSUE TITLE
[feature] redux-ui 功能改进

### ISSUE THREAD

**Issue by magiccaptain** [36node/sketch#109]
### 需求描述

1. assign 中 meta 可以增加一个 merge的参数，表示 当前value 是个对象的时候，新set的value 直接merge到当前的state中。
2. progress 中增加一个status的状态，一个字符串，用来记录当前progress 所进行的状态，比如‘ 正在导入 XXX 个’ 之类的。

**Comment by magiccaptain** [comment]
关于第一条 也可以直接增加一个 merge的action

**Comment by zzswang** [comment]
可以在meta中加一个标准化 所有action 都可能带有 merge 参数

**Comment by zzswang** [comment]
meta: { merge, append }

**Comment by zzswang** [comment]
第二条感觉意义不大
