### ISSUE TITLE
[bug] sketch start不支持static async member

### ISSUE THREAD

**Issue by MiffyLiye** [36node/sketch#122]
### bug 描述

在model层使用static async member后，yarn test和yarn build正常，yarn start失败。

### 环境（选填）

* node 10
* macOS 10.14.5
* bus-op项目
* @36node/sketch ^0.11.12

### 截图/日志

```
miffyliye@light:bus-op (master)$ yarn start
yarn run v1.17.0
$ sketch start
spawn nodemon --harmony -r esm src/server.js
[nodemon] 1.19.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --harmony -r esm src/server.js`
/Users/miffyliye/Code/36node/bus-op/src/models/alert.js:136
  static async createOrAppend(alert) {
               ^

SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
[nodemon] app crashed - waiting for file changes before starting...
```

### 如何重现

1. bus-op的model层使用static async member
2. yarn start

### 期望表现（选填）

正常启动

### 实际表现（选填）

启动失败

**Comment by zzswang** [comment]
嗯嗯 得研究一下

esm 看看怎么支持 static async

**Comment by MiffyLiye** [comment]
https://github.com/standard-things/esm/issues/804
这个issue里说老版本的esm是支持的，新版出现了倒退

**Comment by zzswang** [comment]
@raychenfj 

逢隽，上次你修复 esm 的问题，能否发个pr到这边来

估计能解决这个问题
