### ISSUE TITLE
[feature] upload组件

### ISSUE THREAD

**Issue by lidongbest5** [36node/sketch#137]
### 需求描述

在不同项目中会有使用upload上传功能，包括button的点击上传和在BraftEditor富文本里的上传，图片还需要裁剪功能

需要基于antd upload开发通用的上传组件，上传的目录由之前的七牛云改为阿里云

注意上传组件和表单的结合

### 截止日期（选填）

**Comment by zzswang** [comment]
sketch 中新建一个package

@36node/upload

同时在 tpl-cra-redux 中进行验证

**Comment by zzswang** [comment]
@36node/upload 

1. README.md
2. typings
3. tests

**Comment by zzswang** [comment]
参考之前各个工程里用到 upload 代码，都有一定的封装

比如 zposter-web 或者 https://github.com/zzswang/life-admin

**Comment by zzswang** [comment]
基于 antd/upload
