### ISSUE TITLE
[bug] redux下的ToggleAction赋值不工作

### ISSUE THREAD

**Issue by lalawow** [36node/sketch#167]
### bug 描述

@36node/redux 下的 ToggleAction

import { makeToggle } from "@36node/redux";

const toggle = makeToggle("someKey");
// switch to false
dispath(toggle(false));

但是这里toggle没有实现赋值，确是进行了翻转

**Comment by zzswang** [comment]
应该是 toggle 判断有没有value的时候，没有用 isNil 去判断
