### ISSUE TITLE
[devop] 通过 openapi 自动生成 postman collection 骨架

### ISSUE THREAD

**Issue by zzswang** [36node/sketch#18]
## 背景

以前通过共享 postman 账号，会导致一些问题：

1. 协同编辑存在冲突
2. 测试用例不标准，容易引起混淆
3. 添加测试用例不易建立 issue

## 需求

1. 一个 api 对应 postman 中的一个子文件夹
2. 一个 operation 生成一个 request，看一下 Postman Examples 部分，是否方便生成 examples 和 response 对应起来。 另外数据用变量 参见下一条需求
3. collection 中加入一套 变量，将来可以和 runner 里的 data 配合使用
4. 生成 postman 的 test script 骨架, 判断 response status，应该返回哪些必须的值
5. 需要考虑重复生成，不要覆盖用户编辑过的部分，大体是如果某个节点已经存在，不覆盖，只插入新的。

额外的文案工作: 定义一套 环境变量列表，放在 Readme 中，表示需要开发者自行准备的。比如 token

## 关于 Postman

postman 的使用一直在摸索中，以前有许多使用不当的地方。所以本次 issue 是开放式的，欢迎多讨论。

有几个 postman 上的文章，推荐看一下，对更好的使用 postman 有帮助。

1. [关于 api example 的用法](http://blog.getpostman.com/2017/05/17/mock-responses-in-postman-by-using-examples/)
2. [关于runner 和 data](https://www.getpostman.com/docs/v6/postman/collection_runs/working_with_data_files)
3. [postman 自动化测试](https://segmentfault.com/a/1190000012433650)

## 开发

1. 功能实现在 swagen 子工程里; 脚本加在 tpl-service 中(参加下一条)。
2. 命令 swagen -t postman -s <openapi.yml> -f <folder>
3. 使用 tpl-service 中的 openapi.yml 文件

**Comment by magiccaptain** [comment]
已经pr
