### ISSUE TITLE
[devop] 通过 postman api 导入导出 collection

### ISSUE THREAD

**Issue by zzswang** [36node/sketch#19]
## 背景

打算把 postman collection 文件放在工程里，达到大家协同编辑的目的。

导入导出颇有点麻烦，看看能否提供命令行完成

## 需求

1. sketch 下创建 fastman 工程
2. 提供 fastman import 命令，将 collection 导入到 postman 中去
3. 提供 fastman export 命令，将 postman中指定的 collection 导出

## 开发

1. 执行 sketch init 可以快速创建一个 带 cli 的工程框架

**Comment by magiccaptain** [comment]
fastman 已经开发完 已merge到master
