### ISSUE TITLE
[swagen] 改进生成 postman

### ISSUE THREAD

**Issue by zzswang** [36node/sketch#34]
## 背景

目前用 `swagen postman` 生成的 `postman collection` 文件里 `Bearer auth` 直接放在 `header Authorization` 里了。

但 postman 有一个专用的 auth 字段，可以用于放 Authorization。

## 需求

- 将 security auth 写入 `postman collection` 的 `auth` 中,   如果 security 是全局的，写入 postman folder 下, 如果 security 是某个 operation 特有的，则写入 postman 对应的 api 下
- swagen postman [yamlfile] [targetfile]
   - targetfile default: yaml 中定义的名称
- swagen koa [yamlfile] [dist]
   - dist default 当前目录
- swagen sdk [yamlfile] [dist]
- 修改其他工程里 `package.json` 对应的scripts

**Comment by magiccaptain** [comment]
已完成 https://github.com/36node/sketch/pull/41
