### ISSUE TITLE
脚本基于 openapi.yml 自动生成 sdk

### ISSUE THREAD

**Issue by zzswang** [36node/sketch#4]
## 需求

1. 开发 `swagen` 工程
2. 通过 openapi.yaml 文件自动生成 sdk 相关的代码
3. sdk 代码示例已经在 tpl-react 里，包括 `petstore.js` 和 `.petstore.d.ts`
4. swagen 增加一个命令 swagen sdk，修改文件是 `swagen/bin/swagen.js`
5. 通过新的工具生成 tpl-react/sdk 中的文件，并且确保 tpl-react 能够work

## 高级

目前 swagen 是简单的瀑布流写法，如果有余力，帮改造成 工厂模式。

新的 generator 通过注册引入，而无需去修改 swagen/bin/swagen.js 文件

## 参考

之前我写过一个 go-swagen，工厂模式可以参考 [go-swagen.zip](https://github.com/36node/sketch/files/2174477/go-swagen.zip)

还有一个基于 nodejs 的，仅作参考

https://github.com/swagen/swagen

模板用的 handlebars

**Comment by magiccaptain** [comment]
pr closed
