### ISSUE TITLE
为 service 项目规划 init 脚本框架

### ISSUE THREAD

**Issue by zzswang** [36node/sketch#6]
service 项目本地开发的时候，往往需要连接本地数据库，所以需要一个初始化数据库或者其他存储的脚本框架

本次目标仅考虑 mongodb

## 需求

目标：sketch 中的 tpl-service 

- bin/initdb.js
- 往数据库里塞几组数据方便本地开发

## 开发

参考这个方案

https://stackoverflow.com/questions/41638637/generate-fake-data-with-mongoose-schema

**Comment by magiccaptain** [comment]
已pr
