### ISSUE TITLE
脚手架 react

### ISSUE THREAD

**Issue by zzswang** [36node/sketch#7]
## 背景

计划采用 [poi](https://github.com/egoist/poi)，它是一个类似 create-react-app 的库。

vue 最近也在改版，思路也会模仿 create-react-app。就是这类脚手架工具，不再是简单通过 git clone 下来一串写死的代码。

而是把功能都封装到一些独立的库里，通过调用这些库来完成响应的功能。

那么以后升级啊什么的，都不会有太大的问题

poi 就是关于 script 和 webpack 之类的一个封装

这个框架主要用于 最简单的 单页应用，不考虑 redux 或者 saga 之类的复杂物件。做出来的脚手架页面结构和 create-react-app 类似即可。

## 需求

- 模仿 tpl-service，创建 tpl-react
- circle-ci, build docker
- 完整的 readme
- package.json 的 script 里至少有 npm start   其他模仿 tpl-service
- eslint prettier babel 都和 tpl-service 类似
- 测试 sketch init，选择 react ，可以在本地快速初始化一个 react web 工程
- 封装客户端请求，token 等
- 工程里用 github api 的请求吧

**Comment by magiccaptain** [comment]
已经pr
