### ISSUE TITLE
[feature] 新增 redux-ui 库

### ISSUE THREAD

**Issue by zzswang** [36node/sketch#73]
### 需求描述

对于 toggle、checkbox、modal、progress 等一些简单 ui 的操作，希望能够提供一个统一的库，来提供标准快捷的：

reducer
action
saga
selector

**Comment by magiccaptain** [comment]
modal 和 toggle 其实是一回事

**Comment by zzswang** [comment]
对 modal 和 toggle 是一样的

**Comment by zzswang** [comment]
这个还没做吧?

**Comment by magiccaptain** [comment]
这个issue 先初步封装 toggle assign 和 progress 吧，未来可以再建立issue 加入 cron，timeline，xlsx 等module

**Comment by magiccaptain** [comment]
另外我想把这些model的用法在 tpl-cra-redux 里面做example？
