### ISSUE TITLE
[tpl-cra-redux] 去除path resolve

### ISSUE THREAD

**Issue by zzswang** [36node/sketch#90]
### 需求描述

之前为了整齐好看，在 webpack 里加上了 path resolve，达到效果

```
import ... from "components/a"
```

但是带来了几个问题：

1. 文件路径错误的情况下，调试变得困难
2. 路径不会自动补全了
3. 重命名文件，不会全局自动修改

## 讨论

是否把这个 feature 去了

https://github.com/36node/sketch/pull/76

**Comment by magiccaptain** [comment]
有没有什么方法让vs code 支持这种自动补全？

**Comment by zzswang** [comment]
> 有没有什么方法让vs code 支持这种自动补全？

我也试着找过了，只能单独配置 vs code 里的 config ，感觉有点麻烦。

等周一迭代会议上，可以稍微讨论一下

**Comment by zzswang** [comment]
https://www.jianshu.com/p/552eac30ddbf

**Comment by zzswang** [comment]
经过讨论 做掉它
