### ISSUE TITLE
[bug] query-normalizr 在小程序中无法使用

### ISSUE THREAD

**Issue by raychenfj** [36node/sketch#92]
### bug 描述

因为 lodash 的问题，query-normalizr 在小程序中无法正常使用，无法使用 sdk

![image](https://user-images.githubusercontent.com/3245316/59148127-30ea3300-8a37-11e9-9c2a-528056751a1a.png)

![image](https://user-images.githubusercontent.com/3245316/59148129-4c553e00-8a37-11e9-9ebc-4a59e9b974f7.png)

**Comment by zzswang** [comment]
留个 mark

`microbundle` 不支持 `babel-plugin-lodash` ，否则会自动转换成 modular

啥时候不再需要 babel 呀  😢
